on:
    pull_request:
        branches: [main]
        
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Log Stuff for PULL
          run: |
            echo "${{ toJson(github.event.pull_request) }}"
